name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - name: Upload Test Coverage
        run: bash <(curl -s https://codecov.io/bash) -f packages/perfect-dark-mode/coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: yarn netlify deploy --site 55d1ba1e-2ee7-4201-b555-f6d1720efe44 --dir=packages/docs/dist --prod
      - run: yarn netlify deploy --site 1e21ee7f-6173-4073-9282-ab566c59d6ab --dir=packages/gatsby-plugin-perfect-dark-mode-example/public --prod
      - run: yarn netlify deploy --site 703f9b97-57f8-49df-9a6c-2e3d004196c9 --dir=packages/next-plugin-perfect-dark-mode-example/out --prod
      - run: yarn netlify deploy --site 43103433-c873-422a-ad70-e8be8512fd2f --dir=packages/vue-perfect-dark-mode-example/dist --prod
      - run: yarn netlify deploy --site 9b2e9581-5b79-4d20-9362-4e47ad3dc089 --dir=packages/react-perfect-dark-mode-example/dist --prod
