name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Begin CI...
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node
              uses: actions/setup-node@v1
              with:
                  node-version: '15'

            - name: Install dependencies
              run: yarn install --frozen-lockfile
              env:
                  CI: true

            - name: Build
              run: yarn build
              env:
                  CI: true

            - name: CI
              run: yarn test

            - name: Test Coverage
              run: bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
